### ISSUE TITLE
An error occured

### ISSUE THREAD

**Issue by ackmedikal** [thelia-modules/Dealer#1]
this constant error
installation no
I use
Vesta panel
ubuntu server 14.4 .64
An error occured
Unable to execute SELECT statement [SELECT dealer_tab.ID, dealer_tab.COMPANY, dealer_tab.ADDRESS1, dealer_tab.ADDRESS2, dealer_tab.ZIPCODE, dealer_tab.CITY, dealer_tab.COUNTRY, dealer_tab.DESCRIPTION, dealer_tab.SCHEDULE, dealer_tab.PHONE_NUMBER, dealer_tab.WEB_SITE, dealer_tab.LATITUDE, dealer_tab.LONGITUDE, dealer_tab.CREATED_AT, dealer_tab.UPDATED_AT FROM `dealer_tab` LIMIT 1]

**Comment by Soldras** [comment]
Hi, it is a fresh install or an update ?

If it's an update you have to apply this modification to your database => Dealer/update/sql/update0.2to0.3.sql

**Comment by gillesbourgeat** [comment]
Hello,

if the table does not exist, the sql server generates an exception
You must delete the condition
https://github.com/thelia-modules/Dealer/blob/master/Dealer.php#L27

Or

```php
Try {
   DealerTabQuery::create()->findOne();
} catch(\Exception $e) {
   $database->insertSql(null, [__DIR__ . "/Config/create.sql", __DIR__ . "/Config/insert.sql"]);
}
```
