### ISSUE TITLE
PHP 5.4 incompatibility

### ISSUE THREAD

**Issue by roadster31** [thelia-modules/Dealer#20]
in BaseController (https://github.com/thelia-modules/Dealer/blob/master/Controller/Base/BaseController.php#L42), the following line : 

`const CONTROLLER_CHECK_RESOURCE = [];`

causes this error in PHP 5.4 : 

FatalErrorException in BaseController.php line 42: Compile Error: Arrays are not allowed in class constants

Same probelm here: https://github.com/thelia-modules/Dealer/blob/master/Loop/SchedulesLoop.php#L178 (immediate dereferencing is a 5.5 feature)

**Comment by InformatiqueProg** [comment]
same error

**Comment by roadster31** [comment]
Thelia requires PHP 5.5 now.
