### ISSUE TITLE
Error to switch on Visible

### ISSUE THREAD

**Issue by fafa43** [thelia-modules/Dealer#3]
Deprecated: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0

Warning: Cannot modify header information - headers already sent in Unknown on line 0

Failed to start the session because headers have already been sent by "" at line 0.

**Comment by Soldras** [comment]
To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead.

The issue is in your config
