### ISSUE TITLE
display Dealer in the menu modules

### ISSUE THREAD

**Issue by zzuutt** [thelia-modules/Dealer#6]
Place the module in the Modules menu is not suitable
If you want to give access rights only to this module, you must enable access to **all modules**.
I suggest placing it in the tools menu

**Comment by Soldras** [comment]
Hi,
it's a problem from Thelia not from this module.

**Comment by zzuutt** [comment]
Hi,
if I place Dealer access in the tools menu, 
What are the consequences?

**Comment by Soldras** [comment]
There is no consequences but the right place for a module is on module menu.

We need to improve backoffice template in Thelia to fix this problem.

**Comment by zzuutt** [comment]
ok
thanks
